currency:
  url: ${API_URL:https://api.apilayer.com/exchangerates_data/convert}
  key: ${API_KEY:YEraXsSahmYnVTklREwJ6uvCDwm3VpVS}

server:
  port: 8080

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USER_NAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5431/postgres}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: currency-converter

keycloak:
  auth-server-url: http://172.18.17.177:8081
  autodetect-bearer-only: true
  credentials:
    secret: Qdu5C4z4zLel6thyjr50PVWTEGbff9MO
  realm: Software
  resource: backend
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
      securityCollections:
        - name: SERVICIOS DEL ADMINISTRADOR
          patterns:
            - /api/v1/list
    - auth-roles:
        - USER
      securityCollections:
        - name: SERVICIOS DEL USUARIO
          patterns:
            - /api/v1/convert
